import {
  BedDouble,
  Bike,
  BriefcaseBusiness,
  Building2,
  CalendarCheck,
  Droplets,
  Dumbbell,
  Flower2,
  Gift,
  Hammer,
  Handshake,
  HeartPulse,
  Hotel,
  KeyRound,
  Landmark,
  Laptop,
  Leaf,
  Mail,
  MapPin,
  Megaphone,
  Package,
  Paintbrush,
  PenTool,
  Phone,
  Printer,
  Receipt,
  Scissors,
  Shirt,
  ShoppingBag,
  Smartphone,
  Sparkles,
  Star,
  Store,
  Toolbox,
  Trees,
  Trophy,
  UtensilsCrossed,
  Wallet,
  Wrench,
  type LucideIcon,
} from 'lucide-react'

/**
 * Maps icon names used in data files to Lucide components.
 * Keep icon names in data as plain strings so data stays UI-agnostic.
 */
export const icons: Record<string, LucideIcon> = {
  bed: BedDouble,
  bike: Bike,
  briefcase: BriefcaseBusiness,
  building: Building2,
  calendar: CalendarCheck,
  droplets: Droplets,
  dumbbell: Dumbbell,
  flower: Flower2,
  gift: Gift,
  hammer: Hammer,
  handshake: Handshake,
  heart: HeartPulse,
  hotel: Hotel,
  key: KeyRound,
  landmark: Landmark,
  laptop: Laptop,
  leaf: Leaf,
  mail: Mail,
  mapPin: MapPin,
  megaphone: Megaphone,
  package: Package,
  paintbrush: Paintbrush,
  pen: PenTool,
  phone: Phone,
  printer: Printer,
  receipt: Receipt,
  scissors: Scissors,
  shirt: Shirt,
  shoppingBag: ShoppingBag,
  smartphone: Smartphone,
  sparkles: Sparkles,
  star: Star,
  store: Store,
  toolbox: Toolbox,
  trees: Trees,
  trophy: Trophy,
  utensils: UtensilsCrossed,
  wallet: Wallet,
  wrench: Wrench,
}

export function getIcon(name: string): LucideIcon {
  return icons[name] ?? Sparkles
}
