import { createContext, useContext, useEffect, useState, type ReactNode } from 'react'

export type Language = 'en' | 'sw'

const swahili: Record<string, string> = {
  'Quality Products • Reliable Services • Trusted Solutions': 'Bidhaa Bora • Huduma za Kuaminika • Suluhisho Zinazotegemewa',
  'SHEKILINDI COMPANY LIMITED is a multi-business company delivering quality products, reliable services and trusted solutions through its family of brands.': 'SHEKILINDI COMPANY LIMITED ni kampuni yenye biashara mbalimbali zinazotoa bidhaa bora, huduma za kuaminika na suluhisho zinazotegemewa kupitia chapa zake mbalimbali.',
  Home: 'Nyumbani',
  'About Us': 'Kuhusu Sisi',
  About: 'Kuhusu',
  Businesses: 'Biashara',
  'Our Businesses': 'Biashara Zetu',
  'Products & Services': 'Bidhaa na Huduma',
  Gallery: 'Matunzio',
  Contact: 'Mawasiliano',
  'Get in Touch': 'Wasiliana Nasi',
  'Contact Us': 'Wasiliana Nasi',
  'WhatsApp us': 'Wasiliana nasi WhatsApp',
  'Quick Links': 'Viungo vya Haraka',
  'Who we are': 'Sisi ni Nani',
  'One company. Five trusted businesses.': 'Kampuni moja. Biashara tano zinazoaminika.',
  'SHEKILINDI COMPANY LIMITED brings together a family of businesses — from health and hospitality to hardware, stationery and financial services — all held to the same standard of quality and care.': 'SHEKILINDI COMPANY LIMITED inaunganisha biashara mbalimbali — kuanzia afya na ukarimu hadi vifaa vya ujenzi, vifaa vya maandishi na huduma za kifedha — zote zikizingatia viwango sawa vya ubora na huduma bora.',
  'Meet our business units': 'Kutana na Vitengo Vyetu vya Biashara',
  'Each business serves its own community, backed by the same commitment to reliability.': 'Kila biashara inahudumia jamii yake kwa kujitolea kutoa huduma za kuaminika.',
  Products: 'Bidhaa',
  'Quality products, every day': 'Bidhaa Bora, Kila Siku',
  'A snapshot of what our businesses offer.': 'Muhtasari wa bidhaa zinazotolewa na biashara zetu.',
  'View all products': 'Angalia Bidhaa Zote',
  Services: 'Huduma',
  'Reliable services you can count on': 'Huduma za Kuaminika Unazoweza Kutegemea',
  'From consultations to printing, accommodation and financial services.': 'Kuanzia ushauri wa afya hadi uchapishaji, malazi na huduma za kifedha.',
  'A look inside our world': 'Tazama Shughuli Zetu',
  'People, products and places that make up Shekilindi.': 'Watu, bidhaa na maeneo yanayounda Shekilindi.',
  'Browse the gallery': 'Vinjari Matunzio',
  'Our Story': 'Historia Yetu',
  'Through its family of businesses, the company serves communities with consistency and care, growing steadily while staying true to the values it was founded on.': 'Kupitia biashara zake mbalimbali, kampuni inahudumia jamii kwa uthabiti na uangalifu, ikiendelea kukua huku ikidumisha misingi iliyoanzishwa nayo.',
  'Our Direction': 'Mwelekeo Wetu',
  'Mission & Vision': 'Dhamira na Maono',
  'Our Mission': 'Dhamira Yetu',
  'To deliver quality products and reliable services that make everyday life easier — through businesses people can trust.': 'Kutoa bidhaa bora na huduma za kuaminika zinazorahisisha maisha ya kila siku kupitia biashara zinazotegemewa.',
  'Our Vision': 'Maono Yetu',
  'To be a leading home-grown company known for excellence, honesty and service across every business we operate.': 'Kuwa kampuni inayoongoza iliyoanzishwa hapa nchini, inayojulikana kwa ubora, uaminifu na huduma bora katika kila biashara tunayoendesha.',
  'What guides us': 'Misingi Yetu',
  'Our core values': 'Tunu Zetu Kuu',
  'The principles shared by every business under the Shekilindi name.': 'Kanuni zinazozingatiwa na kila biashara chini ya jina la Shekilindi.',
  Integrity: 'Uadilifu',
  'We do what is right — honestly, fairly and consistently.': 'Tunatenda yaliyo sahihi kwa uaminifu, haki na uthabiti.',
  Care: 'Ujali',
  'Every customer and colleague is treated with respect and warmth.': 'Kila mteja na mfanyakazi anahudumiwa kwa heshima na ukarimu.',
  Excellence: 'Ubora',
  'We hold every business unit to the same high standard of quality.': 'Tunazingatia viwango vya juu vya ubora katika kila kitengo cha biashara.',
  'Business units': 'Vitengo vya Biashara',
  'Communities served': 'Jamii Zinazohudumiwa',
  Many: 'Nyingi',
  'Shared standard': 'Kiwango cha Pamoja',
  One: 'Kimoja',
  "Let's build something together": 'Tujenge Kitu Pamoja',
  'Partner with a company that values quality, consistency and trust.': 'Shirikiana na kampuni inayothamini ubora, uthabiti na uaminifu.',
  'A family of businesses you can trust': 'Familia ya Biashara Unazoweza Kuzitegemea',
  'Five distinct businesses, one shared standard of quality and service.': 'Biashara tano tofauti, zenye viwango vya pamoja vya ubora na huduma.',
  Explore: 'Chunguza',
  'Our business units': 'Vitengo Vyetu vya Biashara',
  'Select a business to learn more about its products, services and story.': 'Chagua biashara ili kujifunza zaidi kuhusu bidhaa, huduma na historia yake.',
  'Quality products. Reliable services.': 'Bidhaa Bora. Huduma za Kuaminika.',
  'Everything our businesses offer, in one place.': 'Bidhaa na huduma zote za biashara zetu, sehemu moja.',
  'What we offer': 'Tunachotoa',
  'A selection of products available across our business units.': 'Baadhi ya bidhaa zinazopatikana katika vitengo vyetu vya biashara.',
  'How we can help': 'Jinsi Tunavyoweza Kusaidia',
  'Professional services delivered by experienced teams.': 'Huduma za kitaalamu zinazotolewa na timu zenye uzoefu.',
  Photos: 'Picha',
  'Company gallery': 'Matunzio ya Kampuni',
  'Select a category, then click any image to view it full size.': 'Chagua kundi, kisha bofya picha yoyote ili kuiona kwa ukubwa kamili.',
  All: 'Zote',
  'Events & People': 'Matukio na Watu',
  'No images in this category yet.': 'Bado hakuna picha katika kundi hili.',
  'Open image:': 'Fungua picha:',
  'Image viewer:': 'Kitazamaji cha picha:',
  'Previous image': 'Picha Iliyotangulia',
  'Next image': 'Picha Inayofuata',
  'Close image viewer': 'Funga kitazamaji cha picha',
  'Welcome to Shekilindi': 'Karibu Shekilindi',
  'Explore Our Businesses': 'Chunguza Biashara Zetu',
  'A growing family of businesses serving customers with consistency, care and professionalism.': 'Familia inayokua ya biashara zinazohudumia wateja kwa uthabiti, uangalifu na weledi.',
  'Five Businesses, One Standard': 'Biashara Tano, Kiwango Kimoja',
  'Everything you need, under one name': 'Unachohitaji Chote, Chini ya Jina Moja',
  'From health and hospitality to hardware, stationery and financial services — we deliver where it matters.': 'Kuanzia afya na ukarimu hadi vifaa vya ujenzi, vifaa vya maandishi na huduma za kifedha — tunatoa huduma panapohitajika.',
  'Built on Trust': 'Tumejengwa kwa Uaminifu',
  'Solutions that grow with you': 'Suluhisho Zinazokua Pamoja Nawe',
  'Whether you are a customer, partner or colleague, you can expect the same dependable service every time.': 'Iwe wewe ni mteja, mshirika au mfanyakazi, unaweza kutegemea huduma bora na ya uhakika kila wakati.',
  'Ready to work with us?': 'Tuko Tayari Kufanya Kazi Pamoja?',
  'Whether you are a customer, partner or supplier — we would love to hear from you.': 'Iwe wewe ni mteja, mshirika au msambazaji — tungependa kusikia kutoka kwako.',
  'Page not found': 'Ukurasa Haujapatikana',
  "The page you are looking for doesn't exist or may have been moved.": 'Ukurasa unaoutafuta haupo au huenda umehamishwa.',
  'Back to Home': 'Rudi Nyumbani',
  'Learn more': 'Jifunze Zaidi',
  'View business': 'Tazama Biashara',
  'All businesses': 'Biashara Zote',
  'Why choose us': 'Kwa Nini Utuchague',
  'Our Services': 'Huduma Zetu',
  'A snapshot of what this business provides to customers.': 'Muhtasari wa huduma zinazotolewa na biashara hii kwa wateja.',
  'Visit us': 'Tutembelee',
  'Get in touch': 'Wasiliana Nasi',
  'Enquire About': 'Ulizia Kuhusu',
  Highlights: 'Vivutio',
  'Previous slide': 'Slaidi Iliyotangulia',
  'Next slide': 'Slaidi Inayofuata',
  'Go to slide': 'Nenda kwenye slaidi',
  'Slide selection': 'Chagua slaidi',
  'Call us': 'Tupigie Simu',
  Locations: 'Maeneo',
  WhatsApp: 'WhatsApp',
  'Email us': 'Tutumie Barua Pepe',
  'Reach us': 'Wasiliana Nasi',
  'Choose whichever channel is most convenient for you.': 'Chagua njia ya mawasiliano inayokufaa zaidi.',
  'Send a message': 'Tuma Ujumbe',
  'Contact form': 'Fomu ya Mawasiliano',
  'Fill in the form below and we will get back to you.': 'Jaza fomu hapa chini nasi tutakujibu.',
  'Full name': 'Jina Kamili',
  Email: 'Barua Pepe',
  'Phone (optional)': 'Simu (si lazima)',
  'Subject (optional)': 'Mada (si lazima)',
  'How can we help?': 'Tunawezaje kukusaidia?',
  Message: 'Ujumbe',
  'Write your message here...': 'Andika ujumbe wako hapa...',
  'Your name': 'Jina lako',
  'Send Message': 'Tuma Ujumbe',
  'Sending...': 'Inatuma...',
  'Message sent!': 'Ujumbe Umetumwa!',
  'Thank you for reaching out — we will get back to you as soon as possible.': 'Asante kwa kuwasiliana nasi — tutakujibu haraka iwezekanavyo.',
  'Send another message': 'Tuma Ujumbe Mwingine',
  'Please enter your name.': 'Tafadhali weka jina lako.',
  'Please enter your email.': 'Tafadhali weka barua pepe yako.',
  'Please enter a valid email address.': 'Tafadhali weka anwani sahihi ya barua pepe.',
  'Please enter your message.': 'Tafadhali andika ujumbe wako.',
  'Your message could not be sent. Please try again.': 'Ujumbe wako haukutumwa. Tafadhali jaribu tena.',
  'Close menu': 'Funga menyu',
  'Open menu': 'Fungua menyu',
  'Main navigation': 'Menyu Kuu',
  'Mobile navigation': 'Menyu ya Simu',
  'Footer navigation': 'Menyu ya Chini',
  'Our businesses': 'Biashara Zetu',
  'Gallery categories': 'Makundi ya Matunzio',
  "We'd love to hear from you": 'Tungependa Kusikia Kutoka Kwako',
  'Questions, partnerships or feedback — reach out and our team will respond as soon as possible.': 'Kwa maswali, ushirikiano au maoni, wasiliana nasi na timu yetu itakujibu haraka iwezekanavyo.',
  'SHEKILINDI COMPANY LIMITED is a multi-business company built on a simple belief: that people deserve quality products, reliable services and trusted solutions — wherever they shop, stay, heal or do business.': 'SHEKILINDI COMPANY LIMITED ni kampuni yenye biashara mbalimbali inayozingatia imani rahisi: watu wanastahili bidhaa bora, huduma za kuaminika na suluhisho zinazotegemewa — wanaponunua, wanapokaa, wanapotafuta tiba au wanapofanya biashara.',
  'See contact page': 'Tazama ukurasa wa mawasiliano',
  'Mon – Sat: 8:00 – 18:00': 'Jumatatu – Jumamosi: 8:00 – 18:00',
  'Mon – Sat: 7:30 – 19:00': 'Jumatatu – Jumamosi: 7:30 – 19:00',
  'Mon – Sat: 8:00 – 18:30': 'Jumatatu – Jumamosi: 8:00 – 18:30',
  'Reception: 24 hours': 'Mapokezi: Saa 24',
  'Mon – Sat: 8:00 – 19:00': 'Jumatatu – Jumamosi: 8:00 – 19:00',
  'All rights reserved.': 'Haki zote zimehifadhiwa.',
  'Learn more about': 'Jifunze zaidi kuhusu',
  'Call to action': 'Wito wa kuchukua hatua',
  'Company Limited': 'Kampuni Limited',
  Language: 'Lugha',
  'Switch language to English': 'Badili lugha iwe Kiingereza',
  'Switch language to Swahili': 'Badili lugha iwe Kiswahili',
  'Natural care, rooted in tradition': 'Huduma za Asili, Zilizojikita kwenye Mila',
  'A modern herbal clinic offering trusted natural remedies and personal wellness consultations delivered with care and professionalism.': 'Kliniki ya kisasa ya tiba asilia inayotoa dawa za asili zinazoaminika na ushauri binafsi wa afya kwa uangalifu na weledi.',
  'Shekilindi Herbal Clinic blends generations of herbal knowledge with modern standards of hygiene and service. Our team guides every visitor through a personalised consultation and recommends remedies suited to their needs — in a calm, welcoming environment.': 'Kliniki ya Tiba Asilia ya Shekilindi inaunganisha maarifa ya tiba asilia ya vizazi vingi na viwango vya kisasa vya usafi na huduma. Timu yetu humshauri kila mgeni na kupendekeza tiba inayokidhi mahitaji yake katika mazingira tulivu na yenye ukarimu.',
  'Personalised wellness consultations': 'Ushauri Binafsi wa Afya',
  'Carefully prepared herbal remedies': 'Dawa za Asili Zilizoandaliwa kwa Uangalifu',
  'Friendly, experienced practitioners': 'Wataalamu Wenye Uzoefu na Ukarimu',
  'Herbal consultations': 'Ushauri wa Tiba Asilia',
  'Natural remedy preparation': 'Maandalizi ya Dawa za Asili',
  'Wellness and lifestyle advice': 'Ushauri wa Afya na Mtindo wa Maisha',
  'Building solutions you can rely on': 'Suluhisho za Ujenzi Unazoweza Kutegemea',
  'A full-range hardware store supplying quality tools, building materials and home improvement essentials at fair prices.': 'Duka kamili la vifaa vya ujenzi linalotoa zana bora, vifaa vya ujenzi na mahitaji ya kuboresha nyumba kwa bei nafuu.',
  'Bosnia Hardware is a one-stop destination for builders, contractors and homeowners. From cement and steel to plumbing, electrical and hand tools, we keep the shelves stocked with brands you can trust — backed by practical advice from our staff.': 'Bosnia Hardware ni kituo kimoja kwa mafundi ujenzi, wakandarasi na wamiliki wa nyumba. Kuanzia saruji na nondo hadi vifaa vya mabomba, umeme na zana za mikono, tunahakikisha bidhaa za chapa zinazoaminika zinapatikana pamoja na ushauri wa vitendo kutoka kwa wafanyakazi wetu.',
  'Wide range of building materials': 'Aina Nyingi za Vifaa vya Ujenzi',
  'Quality hand and power tools': 'Zana Bora za Mikono na za Umeme',
  'Bulk and trade pricing available': 'Bei za Jumla na Biashara Zinapatikana',
  'Building materials supply': 'Ugavi wa Vifaa vya Ujenzi',
  'Tools and hardware': 'Zana na Vifaa vya Ujenzi',
  'Plumbing and electrical supplies': 'Vifaa vya Mabomba na Umeme',
  'Home improvement essentials': 'Mahitaji ya Kuboresha Nyumba',
  'Everything for work, school and print': 'Kila Kitu kwa Kazi, Shule na Uchapishaji',
  'Office supplies, school essentials and professional printing services — helping students, businesses and organisations stay productive.': 'Vifaa vya ofisini, mahitaji ya shule na huduma za kitaalamu za uchapishaji — kuwasaidia wanafunzi, biashara na taasisi kufanya kazi kwa ufanisi.',
  'Bosnia Stationery stocks the desk essentials, art supplies and office equipment that keep work and study moving. Our printing and branding service adds business cards, banners and branded materials produced to a professional standard.': 'Bosnia Stationery ina vifaa muhimu vya mezani, vya sanaa na vya ofisini vinavyosaidia kazi na masomo. Huduma zetu za uchapishaji na chapa zinajumuisha kadi za biashara, mabango na vifaa vyenye chapa vilivyotengenezwa kwa viwango vya kitaalamu.',
  'Office and school supplies': 'Vifaa vya Ofisini na Shule',
  'Professional printing services': 'Huduma za Uchapishaji za Kitaalamu',
  'Custom branding and signage': 'Chapa na Mabango Maalum',
  'Stationery and office supplies': 'Vifaa vya Kuandikia na Ofisini',
  'Printing and photocopying': 'Uchapishaji na Fotokopi',
  'Branding and signage': 'Chapa na Mabango',
  'School and art supplies': 'Vifaa vya Shule na Sanaa',
  'Comfort, hospitality and warm service': 'Starehe, Ukarimu na Huduma ya Upendo',
  'A welcoming hotel offering clean, comfortable rooms, delicious dining and attentive service for business and leisure travellers.': 'Hoteli yenye ukarimu inayotoa vyumba safi na vya starehe, chakula kitamu na huduma makini kwa wasafiri wa kikazi na mapumziko.',
  'Triple Twelve Hotel provides a restful stay with well-kept rooms, friendly staff and convenient amenities. Whether you are visiting for business or leisure, our team makes sure every detail — from check-in to checkout — feels effortless.': 'Triple Twelve Hotel hutoa malazi ya kustarehesha, vyumba vilivyotunzwa vizuri, wafanyakazi wenye urafiki na huduma zinazofaa. Iwe umetembelea kwa kazi au mapumziko, timu yetu huhakikisha kila hatua — kuanzia kuingia hadi kutoka — ni rahisi.',
  'Comfortable, well-kept rooms': 'Vyumba vya Starehe Vilivyotunzwa Vizuri',
  'On-site dining and refreshments': 'Chakula na Viburudisho Vinapatikana Hapa',
  'Warm, attentive hospitality': 'Ukarimu na Huduma Makini',
  Accommodation: 'Malazi',
  'Dining and room service': 'Chakula na Huduma ya Chumbani',
  'Events and gatherings': 'Matukio na Mikusanyiko',
  'Guest support': 'Huduma kwa Wageni',
  'Financial services, closer to you': 'Huduma za Kifedha, Karibu Nawe',
  'A convenient neighbourhood wakala providing money transfers, payments and everyday financial services you can trust.': 'Wakala wa karibu anayetoa huduma za kutuma pesa, malipo na huduma za kifedha za kila siku unazoweza kuziamini.',
  'Shekilindi Wakala brings essential financial services to the heart of the community. Customers can send and receive money, pay bills and access everyday transactions quickly, securely and with a smile.': 'Shekilindi Wakala huleta huduma muhimu za kifedha karibu na jamii. Wateja wanaweza kutuma na kupokea pesa, kulipa bili na kufanya miamala ya kila siku kwa haraka, usalama na tabasamu.',
  'Fast money transfers': 'Uhamisho wa Pesa wa Haraka',
  'Bill payments and top-ups': 'Malipo ya Bili na Vocha',
  'Secure, friendly service': 'Huduma Salama na ya Kirafiki',
  'Money transfers': 'Uhamisho wa Pesa',
  'Bill and utility payments': 'Malipo ya Bili na Huduma',
  'Mobile money services': 'Huduma za Pesa kwa Simu',
  'Account assistance': 'Msaada wa Akaunti',
  'Shekilindi Naturals Seaweed Skin Oil': 'Mafuta ya Mwani ya Ngozi ya Shekilindi Naturals',
  'Shekilindi Naturals CocoGlow Oil': 'Mafuta ya Nazi CocoGlow ya Shekilindi Naturals',
  'Power & Hand Tools': 'Zana za Umeme na za Mikono',
  'Building Materials': 'Vifaa vya Ujenzi',
  'Office & School Supplies': 'Vifaa vya Ofisini na Shule',
  'Pens, Markers & Art Supplies': 'Kalamu, Markus na Vifaa vya Sanaa',
  'Guest Rooms': 'Vyumba vya Wageni',
  'Dining & Refreshments': 'Chakula na Viburudisho',
  'Money Transfer Services': 'Huduma za Uhamisho wa Pesa',
  'Bills & Payments': 'Bili na Malipo',
  'Health & Wellness': 'Afya na Ustawi',
  Hardware: 'Vifaa vya Ujenzi',
  Stationery: 'Vifaa vya Kuandikia',
  Hospitality: 'Ukarimu',
  Financial: 'Huduma za Kifedha',
  'Nourishing seaweed skin oil from our Shekilindi Naturals range — moisturising, hydrating and renewing for everyday skin and hair care.': 'Mafuta ya ngozi yenye virutubisho ya mwani kutoka Shekilindi Naturals — hulainisha, huongeza unyevunyevu na kusaidia kutunza ngozi na nywele kila siku.',
  'Natural, pure and nourishing coconut oil for skin and hair — a daily favourite from our Shekilindi Naturals range.': 'Mafuta ya nazi safi na yenye virutubisho kwa ngozi na nywele — chaguo pendwa la kila siku kutoka Shekilindi Naturals.',
  'Drills, cutters, wrenches and everyday hand tools from dependable brands.': 'Dira, vikataji, spana na zana za mikono za kila siku kutoka chapa zinazoaminika.',
  'Cement, timber, roofing and finishing materials for projects of every size.': 'Saruji, mbao, vifaa vya kuezekea na vya umaliziaji kwa miradi ya ukubwa wowote.',
  'Notebooks, files, writing instruments and desk essentials for work and study.': 'Daftari, mafaili, vifaa vya kuandikia na mahitaji ya mezani kwa kazi na masomo.',
  'Pens, markers, highlighters, colours and art essentials for school, home and the office.': 'Kalamu, markus, kalamu za kuangazia, rangi na vifaa vya sanaa kwa shule, nyumbani na ofisini.',
  'Clean, comfortable rooms prepared for a restful stay — single and double options.': 'Vyumba safi na vya starehe vilivyoandaliwa kwa mapumziko — vinapatikana vya mtu mmoja na wawili.',
  'Freshly prepared meals and refreshments served in a relaxed setting.': 'Milo mipya na viburudisho vinavyotolewa katika mazingira tulivu.',
  'Send and receive money quickly and securely at your neighbourhood wakala.': 'Tuma na pokea pesa kwa haraka na usalama kupitia wakala wa karibu.',
  'Convenient payment of utility bills, subscriptions and everyday transactions.': 'Lipa kwa urahisi bili za huduma, usajili na miamala ya kila siku.',
  'Herbal Consultations': 'Ushauri wa Tiba Asilia',
  'One-on-one sessions with experienced practitioners to find the right natural approach for you.': 'Mashauri binafsi na wataalamu wenye uzoefu ili kupata njia sahihi ya tiba asilia kwako.',
  'Wellness & Lifestyle Advice': 'Ushauri wa Afya na Mtindo wa Maisha',
  'Practical guidance on nutrition, habits and everyday routines to support your wellbeing.': 'Mwongozo wa vitendo kuhusu lishe, tabia na ratiba za kila siku ili kuimarisha afya yako.',
  'Building Materials Supply': 'Ugavi wa Vifaa vya Ujenzi',
  'Reliable supply of cement, timber, roofing and finishing materials for any project.': 'Ugavi wa kuaminika wa saruji, mbao, vifaa vya kuezekea na vya umaliziaji kwa mradi wowote.',
  'Tools & Hardware': 'Zana na Vifaa vya Ujenzi',
  'Quality hand tools, power tools and fixings for professionals and DIY enthusiasts.': 'Zana bora za mikono, zana za umeme na vifaa vya kufungia kwa wataalamu na wanaopenda kujifanyia kazi.',
  'Printing & Photocopying': 'Uchapishaji na Fotokopi',
  'Fast, affordable printing and photocopying for documents of all sizes.': 'Uchapishaji na fotokopi za haraka na za bei nafuu kwa nyaraka za ukubwa wote.',
  'Branding & Signage': 'Chapa na Mabango',
  'Business cards, banners and branded materials that make your business stand out.': 'Kadi za biashara, mabango na vifaa vyenye chapa vinavyoitofautisha biashara yako.',
  'Comfortable rooms with warm hospitality for business and leisure travellers.': 'Vyumba vya starehe na ukarimu kwa wasafiri wa kikazi na mapumziko.',
  'Dining & Events': 'Chakula na Matukio',
  'Freshly prepared meals, refreshments and a welcoming space for small gatherings.': 'Milo mipya, viburudisho na sehemu yenye ukarimu kwa mikusanyiko midogo.',
  'Money Transfers': 'Uhamisho wa Pesa',
  'Send and receive money quickly and securely through trusted networks.': 'Tuma na pokea pesa kwa haraka na usalama kupitia mitandao inayoaminika.',
  'Bill & Utility Payments': 'Malipo ya Bili na Huduma',
  'Settle utility bills, airtime and everyday payments without the long queues.': 'Lipa bili za huduma, vocha na malipo ya kila siku bila kusubiri foleni ndefu.',
  'Our Team': 'Timu Yetu',
  'The Shekilindi team at our Herbal Clinic and Research Center.': 'Timu ya Shekilindi katika Kliniki na Kituo chetu cha Utafiti wa Tiba Asilia.',
  'Welcome Address': 'Hotuba ya Karibu',
  'Welcoming guests at a special event at our Herbal Clinic and Research Center.': 'Kuwakaribisha wageni katika tukio maalum kwenye Kliniki na Kituo chetu cha Utafiti wa Tiba Asilia.',
  'Guest Speaker': 'Mzungumzaji Mgeni',
  'A guest speaker addressing the gathering.': 'Mzungumzaji mgeni akilihutubia kusanyiko.',
  'Clinic & Research Center': 'Kliniki na Kituo cha Utafiti',
  'Our Shekilindi Herbal Clinic and Research Center storefront.': 'Jengo la Kliniki na Kituo cha Utafiti wa Tiba Asilia cha Shekilindi.',
  'Community Turnout': 'Mahudhurio ya Jamii',
  'Neighbours, customers and well-wishers joining the celebration.': 'Majirani, wateja na marafiki wakishiriki katika sherehe.',
  'Wakala Services Point': 'Kituo cha Huduma za Wakala',
  'Mobile money and bill payments at our wakala service point.': 'Huduma za pesa kwa simu na malipo ya bili katika kituo chetu cha wakala.',
  'Media Interviews': 'Mahojiano na Vyombo vya Habari',
  'Our team speaking with local TV and radio stations.': 'Timu yetu ikizungumza na vituo vya televisheni na redio vya eneo letu.',
}

interface LanguageContextValue {
  language: Language
  setLanguage: (language: Language) => void
  t: (text: string) => string
}

const LanguageContext = createContext<LanguageContextValue | null>(null)

function getInitialLanguage(): Language {
  try {
    return window.localStorage.getItem('shekilindi-language') === 'sw' ? 'sw' : 'en'
  } catch {
    return 'en'
  }
}

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguage] = useState<Language>(getInitialLanguage)
  const t = (text: string) => (language === 'sw' ? swahili[text] ?? text : text)

  useEffect(() => {
    document.documentElement.lang = language
    try {
      window.localStorage.setItem('shekilindi-language', language)
    } catch {
      // Keep language selection usable when storage is unavailable.
    }
  }, [language])

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  )
}

export function useLanguage() {
  const context = useContext(LanguageContext)
  if (!context) throw new Error('useLanguage must be used within LanguageProvider')
  return context
}